'use client';
import {useState} from 'react';
import {INDUSTRIES,SOFT_SKILLS,FOCUS,AUTONOMY,COLLABORATION} from '@/lib/candidate-survey';
import {Checkbox} from '@/components/ui/checkbox';
export function SoftSkillsField({value=[],onChange}:{value:string[];onChange:(v:string[])=>void}){return <fieldset className="stack-field"><legend>Софт-скиллы · выберите хотя бы один</legend><p className="muted">Самооценка: эти навыки не подтверждаются техническим тестом.</p><div className="stack-options">{SOFT_SKILLS.map(s=><label className="stack-option" key={s}><Checkbox checked={value.includes(s)} onCheckedChange={v=>onChange(v===true?[...new Set([...value,s])]:value.filter(x=>x!==s))}/><span>{s}</span></label>)}</div></fieldset>;}
export default function CandidateSurvey({profile,grade,busy,onStart}:{profile:any;grade:string;busy:boolean;onStart:(v:any)=>Promise<void>}){
 const [industry,setIndustry]=useState(profile.industry||''),[specialization,setSpecialization]=useState(profile.role),[focus,setFocus]=useState(''),[autonomy,setAutonomy]=useState(''),[collaboration,setCollaboration]=useState('');
 function choice(label:string,value:string,values:string[],change:(v:string)=>void){return <label className="field"><span>{label}</span><select required value={value} onChange={e=>change(e.target.value)}><option value="" disabled>Выберите ответ</option>{values.map(v=><option key={v} value={v}>{v}</option>)}</select></label>;}
 const cooldown=profile.lastGradeChange&&Date.now()-profile.lastGradeChange<90*86400000;
 return <form onSubmit={async e=>{e.preventDefault();await onStart({action:'questionnaire',industry,role:specialization,grade,focus,autonomy,collaboration});}}><h3>Шаг 1. Короткий опрос</h3><p className="muted">Ответы сохранятся в истории. Категория и грейд подтверждаются следующим техническим тестом, а не самооценкой.</p>{specialization!==profile.role&&<p className="notice">Смена специализации сбросит прежний подтверждённый грейд. Интервал смены грейда сохранится.</p>}<div className="form-grid">{choice('В какой отрасли хотите работать?',industry,INDUSTRIES,setIndustry)}{choice('Какая ваша специализация?',specialization,Object.keys(FOCUS),v=>{setSpecialization(v);setFocus('');})}{choice('Какие задачи вам ближе?',focus,FOCUS[specialization]||[],setFocus)}{choice('Насколько самостоятельно решаете задачи?',autonomy,AUTONOMY,setAutonomy)}{choice('Как обычно взаимодействуете с командой?',collaboration,COLLABORATION,setCollaboration)}</div><p>Выбранный уровень проверки: <b>{grade}</b></p><button type="submit" className="primary" disabled={busy||!!cooldown||!industry||!focus||!autonomy||!collaboration||!profile.softSkills?.length}>Сохранить опрос и начать тест</button>{!profile.softSkills?.length&&<p className="notice">Сначала выберите софт-скиллы и сохраните профиль.</p>}</form>;
}

export function SurveySummary({value}:{value:any}){return value?<details className="survey-summary"><summary>Ответы опроса · {value.role} / {value.grade}</summary><p><b>Отрасль:</b> {value.industry}</p><p><b>Задачи:</b> {value.focus}</p><p><b>Самостоятельность:</b> {value.autonomy}</p><p><b>Команда:</b> {value.collaboration}</p><small>Самоописание · {new Date(value.completedAt).toLocaleDateString('ru-RU')}</small></details>:null;}
