'use client';
import {useEffect,useRef,useState} from 'react';
export default function EmailVerification({email,available,verified,required=false,compact=false,autoSend=false}:{email:string;available:boolean;verified:boolean;required?:boolean;compact?:boolean;autoSend?:boolean}){
 const [code,setCode]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[retryAt,setRetryAt]=useState(0),[seconds,setSeconds]=useState(0);const started=useRef('');
 async function action(name:string){setBusy(true);if(name==='send'){const until=Date.now()+60000;setRetryAt(until);setSeconds(60);try{sessionStorage.setItem('fsp-email-send:'+email,String(until));}catch{}setMessage('Отправляем код на вашу почту…');}try{const r=await fetch('/api/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:name,code})});const d=await r.json();if(!r.ok)throw Error(d.error);if(name==='verify')window.location.reload();else setMessage('Код отправлен. Проверьте входящие и папку «Спам».');}catch(e:any){setMessage(e.message||'Не удалось отправить запрос. Попробуйте ещё раз.');}finally{setBusy(false);}}
 useEffect(()=>{if(!autoSend||!available||verified||!email||started.current===email)return;started.current=email;let until=0;try{until=Number(sessionStorage.getItem('fsp-email-send:'+email))||0;}catch{}if(until>Date.now()){setRetryAt(until);setSeconds(Math.ceil((until-Date.now())/1000));setMessage('Код уже запрошен. Проверьте входящие и папку «Спам».');return;}void action('send');},[autoSend,available,verified,email]);
 useEffect(()=>{if(!retryAt)return;const tick=()=>setSeconds(Math.max(0,Math.ceil((retryAt-Date.now())/1000)));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[retryAt]);
 if(verified)return <p className="notice">Почта подтверждена: {email}</p>;
 return <section className="panel email-verification">{!compact&&<h2>Подтверждение почты</h2>}<p>{email}</p><p className="muted">{available?(required?'Для продолжения введите код из письма.':'Подтвердите адрес кодом из письма.'):'Почтовый сервис ещё не подключён. Адрес сохранён, но его владение не подтверждено.'}</p>{available&&<><form onSubmit={e=>{e.preventDefault();void action('verify');}}><label className="field"><span>Код из письма</span><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} required autoComplete="one-time-code"/></label><button className="primary" disabled={busy||code.length!==6}>Подтвердить</button></form>{seconds>0?<p className="muted">Отправить повторно можно через {seconds} сек.</p>:(!autoSend||retryAt>0)&&<button type="button" className="secondary" disabled={busy} onClick={()=>void action('send')}>{autoSend||retryAt?'Отправить код повторно':'Отправить код'}</button>}</>}{message&&<p role="status">{message}</p>}</section>;
}

