'use client';
import {useState} from 'react';
const criteria=['Корректность и требования','Надёжность и крайние случаи','Объяснение и воспроизводимость'];
export function ReviewView({review}:{review:any}){return <section><h3>Оценка работодателя: {review.score}/6</h3>{criteria.map((c,i)=><p key={c}>{c}: {review.ratings[i]}/2</p>)}<p>{review.comment}</p><small>Эта оценка относится к конкретному заданию и не меняет общий грейд.</small></section>;}
export function ReviewForm({invitation,busy,onSubmit}:any){const [ratings,setRatings]=useState<number[]>(invitation.review?.ratings||[0,0,0]),[comment,setComment]=useState(invitation.review?.comment||'');return <form onSubmit={e=>{e.preventDefault();onSubmit({action:'reviewSolution',id:invitation.id,ratings,comment});}}><h3>Оценить решение</h3><p>0 — не выполнено, 1 — частично, 2 — выполнено.</p>{criteria.map((c,i)=><label className="field" key={c}><span>{c}</span><select value={ratings[i]} onChange={e=>setRatings(ratings.map((v,j)=>i===j?Number(e.target.value):v))}>{[0,1,2].map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}<label className="field"><span>Обратная связь кандидату</span><textarea maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label><button className="primary" disabled={busy}>Сохранить оценку</button></form>;}
export function SolutionView({solution}:{solution:any}){return <section className="solution-view"><h3>Решение кандидата</h3><p className="muted">Отправлено {new Date(solution.submittedAt).toLocaleString('ru-RU')}</p><p className="project-text">{solution.text}</p>{solution.url&&<a href={solution.url} target="_blank" rel="noopener noreferrer">Открыть результат или код</a>}</section>;}
export function SolutionForm({invitation,busy,onSubmit}:{invitation:any;busy:boolean;onSubmit:(body:any)=>Promise<any>}){
 const [text,setText]=useState(invitation.solution?.text||''),[url,setUrl]=useState(invitation.solution?.url||'');
 return <form className="solution-form" onSubmit={async e=>{e.preventDefault();await onSubmit({action:'submitSolution',id:invitation.id,text,url});}}><h3>{invitation.solution?'Обновить решение':'Ваше решение'}</h3><label className="field"><span>Ответ и описание решения</span><textarea required maxLength={15000} placeholder="Напишите решение, поясните подход и результат" value={text} onChange={e=>setText(e.target.value)}/></label><label className="field"><span>Ссылка на результат или исходный код (необязательно)</span><input type="url" maxLength={1000} placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)}/></label><p className="muted">Решение увидит только работодатель, отправивший это задание. После отправки его можно обновить.</p><button type="submit" className="primary" disabled={busy||!text.trim()}>{invitation.solution?'Обновить решение':'Отправить решение'}</button></form>;
}
