import {GRADE_BANK} from './assessment-bank';
import {legacyQuestions} from './domain';
export const ASSESSMENT_VERSION=2;
export const PASS_SCORE:Record<string,number>={Junior:70,Middle:80,Senior:87};
export function shuffle<T>(items:T[],rng=()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function practicalQuestions(role:string,grade:string,rng=()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296){
 const a=4+Math.floor(rng()*16),b=2+Math.floor(rng()*7),c=2+Math.floor(rng()*5);
 const rows:Record<string,Record<string,[string,string,number][]>>={
 Backend:{
 Junior:[['Пагинация',`Страницы нумеруются с 1. Размер страницы ${a}, нужна страница ${b}. Какой OFFSET?`,(b-1)*a],['Пакеты',`Есть ${a*b+1} записей. Один пакет содержит не более ${a} записей. Сколько пакетов нужно?`,b+1],['Остатки',`На складе ${a*b} единиц. Успешно продано ${a} и затем ${b}. Какой остаток?`,a*b-a-b],['TTL',`Запись создана в секунду ${a*100}; TTL ${b*10} секунд. В какую секунду она истечёт?`,a*100+b*10],['Лимиты',`Лимит ${a*b} запросов в окно. Выполнено ${a}. Сколько осталось в этом окне?`,a*b-a]],
 Middle:[['Оптимистическая блокировка',`Версия строки равна ${a}. ${b} параллельных UPDATE используют WHERE version=${a} и увеличивают version на 1. Сколько запросов успешно изменят строку?`,1],['Нагрузка',`Стабильный поток ${a*10} запросов/с, среднее время 0.${b} с. По L=λW сколько запросов в среднем в работе?`,a*b],['Backoff',`Начальная задержка ${a} мс. После каждой неудачи удваивается. Какова задержка перед третьим повтором (первый: ${a})?`,a*4],['Индекс',`В таблице ${a*b*100} строк, ровно ${a*100} соответствуют фильтру. Какой процент соответствует? Округлите до 2 знаков.`,100/b],['Rate limit',`В token bucket ${a} токенов; ёмкость ${a+b}; пополнение 1/с. Через ${b} секунд поступило ${c} запросов по 1 токену. Сколько токенов останется после принятых запросов?`,Math.max(0,a+b-c)]],
 Senior:[['Кворум',`В ${b*2+1} репликах требуется строгое большинство для записи. Сколько подтверждений нужно?`,b+1],['Бюджет ошибок',`За окно ${a*1000} запросов. SLO успешности 99%. Сколько неуспешных запросов укладывается в бюджет?`,a*10],['Bottleneck',`Три последовательных стадии независимо обслуживают ${a*10}, ${a*10+b*10} и ${a*10+c*10} задач/с. Какова максимальная устойчивая пропускная способность конвейера?`,a*10],['Retry budget',`За интервал ${a*100} первичных запросов. Бюджет повторов 10% от первичных. Уже сделано ${b} повторов. Сколько ещё разрешено?`,a*10-b],['Ёмкость',`Один экземпляр обслуживает ${a} запросов/с при целевой загрузке. Пик ${a*b+1}. Сколько экземпляров минимум нужно?`,b+1]]},
 Frontend:{
 Junior:[['CSS',`У элемента content-box ширина ${a*10}px, padding ${b}px с каждой стороны, border ${c}px с каждой стороны. Какова внешняя ширина без margin?`,a*10+2*b+2*c],['JavaScript',`let x=${a}; x += ${b}; x *= 2; Какое значение x?`,(a+b)*2],['Массивы',`Массив содержит ${a*b} элементов. Удалили ${a}, добавили ${b}. Какова длина?`,a*b-a+b],['Сетка',`В строке ${b} карточек. Всего ${a*b+1} карточек. Сколько строк нужно?`,a+1],['Изображения',`Изображение шириной ${a*10}px и высотой ${a*5}px уменьшили до ширины ${b*10}px с сохранением пропорций. Высота?`,b*5]],
 Middle:[['React',`State=${a}. Выполнены ${b} функциональных обновлений setState(x=>x+1). Итоговое значение?`,a+b],['Виртуализация',`Видимы ${a} строк, overscan ${b} сверху и снизу; границы списка далеко. Сколько строк рендерится?`,a+2*b],['Debounce',`Последний ввод в момент ${a*100} мс. Debounce ${b*100} мс, новых событий нет. Когда вызовется обработчик?`,(a+b)*100],['Сеть',`Последовательно загружены ${a} файлов по ${b} КБ без сжатия и повторов. Всего КБ?`,a*b],['CSS',`Контейнер ${a*10+b*2}px, gap между двумя колонками ${b*2}px. Колонки равные, без padding. Ширина одной?`,a*5]],
 Senior:[['Бюджет JS',`Лимит initial JS ${a*10} КБ. Shell ${a*5} КБ, критичный route ${b} КБ. Сколько КБ бюджета осталось?`,a*5-b],['Long tasks',`В окне ${a*100} мс главный поток занят ${b*10} мс. Сколько мс остаётся свободным?`,a*100-b*10],['Ошибки',`В релизе ${a*1000} сессий. ${b*10} завершились критической ошибкой. Доля ошибок в процентах? До 2 знаков.`,b/a],['Кэш',`При TTL ${a} секунд ключ обновлён в момент ${b*100}. В какую секунду истечёт без продления?`,b*100+a],['Виртуализация',`Из ${a*b*100} строк рендерится ${a*b}. Какой процент исходных DOM строк остаётся?`,1]]},
 'Data Science':{
 Junior:[['Медиана',`Найдите медиану: ${a}, ${a+2}, ${a+4}, ${a+6}, ${a+100}.`,a+4],['MAE',`Две абсолютные ошибки: ${a} и ${b}. Каков MAE?`,(a+b)/2],['Recall',`TP=${a}, FN=${a}. Recall в процентах?`,50],['Train split',`Датасет ${a*100} строк. В train 80%. Сколько строк в train?`,a*80],['Среднее',`Среднее двух наблюдений ${a} и ${a+b*2}?`,a+b]],
 Middle:[['Precision',`TP=${a}, FP=${a*b}. Precision в процентах? До 2 знаков.`,100/(b+1)],['F1',`Precision=0.5, recall=1. F1=2PR/(P+R). Найдите F1 до 2 знаков.`,2/3],['Lift',`Конверсия A=${a}%, B=${a+b}%. Относительный рост в процентах? До 2 знаков.`,100*b/a],['Взвешенный MAE',`У сегмента 1 ${a} объектов и MAE=2; у сегмента 2 ${a*b} объектов и MAE=4. Общий MAE? До 2 знаков.`,(2+4*b)/(1+b)],['Holdout',`В ряду ${a*10} дней последние ${b} идут в test. Сколько дней останется для train?`,a*10-b]],
 Senior:[['Стоимость ошибок',`FN=${a}, FP=${b}, стоимость FN=${c*10}, FP=2. Общая стоимость?`,a*c*10+b*2],['IPW',`Для наблюдения propensity=1/${b}. Вес обратной вероятности 1/p?`,b],['Покрытие',`Из ${a*10} наблюдений ${a*9} попали в прогнозный интервал. Покрытие в процентах?`,90],['Precision@K',`В первых ${b*2} рекомендациях релевантны ${b}. Precision@K в процентах?`,50],['Смесь сегментов',`В сегменте A ${a} объектов и ошибка 1; в B ${a*b} и ошибка 3. Средняя ошибка? До 2 знаков.`,(1+3*b)/(1+b)]]}};
 return rows[role][grade].map(([skill,text,answer])=>({id:crypto.randomUUID(),skill,text,kind:'number',answer:Math.round(answer*100)/100,tolerance:0.011}));
}
export function generateAssessment(role:string,grade:string){
 const choices=grade==='Junior'?shuffle(legacyQuestions(role,grade)).slice(0,10).map(q=>({...q,kind:'choice'})):GRADE_BANK[role][grade].map(row=>{const options=shuffle(row.slice(2));return {id:crypto.randomUUID(),skill:row[0],text:row[1],kind:'choice',options,answer:options.indexOf(row[2])};});
 return shuffle([...choices,...practicalQuestions(role,grade)]);
}
export function correctAnswer(q:any,value:any){if(q.kind!=='number')return Number.isInteger(value)&&value===q.answer;if(typeof value!=='string'||!/^[-+]?\d+(?:[.,]\d+)?$/.test(value.trim()))return false;return Math.abs(Number(value.trim().replace(',','.'))-q.answer)<=q.tolerance;}
export function evaluate(qs:any[],answers:any[],grade:string){const marks=qs.map((q,i)=>correctAnswer(q,answers[i]));const practical=qs.filter(q=>q.kind==='number').length;const practicalCorrect=qs.filter((q,i)=>q.kind==='number'&&marks[i]).length;const score=Math.round(marks.filter(Boolean).length/qs.length*100);return {score,passed:score>=PASS_SCORE[grade]&&(!practical||practicalCorrect>=3),practicalCorrect,practicalTotal:practical,skills:qs.map((q,i)=>({skill:q.skill,correct:marks[i],kind:q.kind||'choice'}))};}
