import {mailReady} from './mail';
import {env} from 'cloudflare:workers';
export function database(){if(!env.DB)throw new Error('Хранилище недоступно');return env.DB;}
export async function list(owner:string,kind:string){const r=await database().prepare('SELECT data FROM records WHERE owner = ? AND kind = ? ORDER BY updated DESC').bind(owner,kind).all<{data:string}>();return r.results.map(r=>JSON.parse(r.data));}
export async function read(owner:string,kind:string,id:string){const r=await database().prepare('SELECT data FROM records WHERE owner = ? AND kind = ? AND id = ?').bind(owner,kind,owner+':'+kind+':'+id).first<{data:string}>();return r?JSON.parse(r.data):null;}
export function statement(owner:string,kind:string,v:any){return database().prepare('INSERT INTO records (id,owner,kind,data,updated) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated=excluded.updated').bind(owner+':'+kind+':'+v.id,owner,kind,JSON.stringify(v),Date.now());}
export async function put(owner:string,kind:string,v:any){await statement(owner,kind,v).run();return v;}
export async function publicProfiles(){const r=await database().prepare("SELECT owner,data FROM records WHERE kind='profile' AND json_extract(data,'$.published')=1 AND json_extract(data,'$.consent')=1 AND json_extract(data,'$.grade') IS NOT NULL AND owner IN (SELECT id FROM users WHERE role='candidate')").all<{owner:string;data:string}>();const profiles=r.results.map(r=>({...JSON.parse(r.data),id:r.owner}));if(!mailReady())return profiles;const verified=await database().prepare("SELECT owner FROM records WHERE kind='emailVerification' AND json_extract(data,'$.verified')=1").all<{owner:string}>();const allowed=new Set(verified.results.map(v=>v.owner));return profiles.filter(p=>allowed.has(p.id));}
export async function candidateInbox(owner:string){const r=await database().prepare("SELECT data FROM records WHERE kind='invitation' AND json_extract(data,'$.candidateOwner')=? ORDER BY updated DESC").bind(owner).all<{data:string}>();return r.results.map(r=>JSON.parse(r.data));}
export async function candidateInvitation(owner:string,id:string){const r=await database().prepare("SELECT owner,data FROM records WHERE kind='invitation' AND json_extract(data,'$.candidateOwner')=? AND json_extract(data,'$.id')=?").bind(owner,id).first<{owner:string;data:string}>();return r?{employer:r.owner,value:JSON.parse(r.data)}:null;}
