import {validateEducation} from '@/lib/education';
import {validateCandidateFields,validateSurvey} from '@/lib/candidate-survey';
import {analyzeNeed} from '@/lib/need-analysis';
import {mailReady} from '@/lib/mail';
import {evaluate,ASSESSMENT_VERSION} from '@/lib/assessment';
import {validatePortfolio} from '@/lib/portfolio';
import {ASSIGNMENTS} from '@/lib/assignments';
import {getUser} from '@/lib/auth';
import {list,read,put,statement,database,publicProfiles,candidateInbox,candidateInvitation} from '@/lib/store';
import {seed,rank,questions,roles,grades} from '@/lib/domain';
export const dynamic='force-dynamic';
function fail(message:string,status=400){return Response.json({error:message},{status});}
async function identity(){const u=await getUser();if(u&&mailReady()&&!u.emailVerified)return null;return u?.userId;}
async function role(owner:string){const user=await getUser();return user?.role;}
export async function GET(req:Request){try{const owner=await identity();if(!owner)return fail('Войдите в систему',401);const url=new URL(req.url);const r=await role(owner);const invitations=await list(owner,'invitation');const profile=await read(owner,'profile','me');const company=await read(owner,'company','main')||{id:'main',name:'Команда продукта',description:'Разрабатываем цифровые сервисы',contact:'hr@example.test'};
 if(r==='candidate')return Response.json({role:r,profile,company,questionnaire:await read(owner,'questionnaire','main'),invitations:await candidateInbox(owner),candidates:[]});
 const need={role:url.searchParams.get('role')||'Backend',grade:url.searchParams.get('grade')||'Middle',stack:url.searchParams.get('stack')||'',format:url.searchParams.get('format')||''};
 const candidates=[...seed(),...await publicProfiles()].map(c=>{const {email,...safe}=c;const accepted=invitations.some(i=>i.candidateId===c.id&&i.status==='accepted');return {...safe,...(accepted?{email}:{}),match:rank(c,need)};}).filter(c=>(!url.searchParams.get('strict')||(c.role===need.role&&c.grade===need.grade))&&(!url.searchParams.get('fsp')||c.fsp.length>0)&&(!url.searchParams.get('format')||c.format===need.format)).sort((a,b)=>b.match.value-a.match.value);
 return Response.json({role:r,company,candidates,invitations,profile:null});}catch(e){console.error(e);return fail('Не удалось загрузить данные. Попробуйте ещё раз.',503);}}
export async function POST(req:Request){try{const owner=await identity();if(!owner)return fail('Войдите в систему',401);if(new URL(req.url).origin!==req.headers.get('origin'))return fail('Недопустимый источник запроса',403);const b:any=await req.json();const current=await role(owner);
 if(b.action==='previewAssessment'){if(current!=='employer')return fail('Только для работодателя',403);if(typeof b.description!=='string'||b.description.trim().length<20||b.description.length>3000)return fail('Опишите потребность: от 20 до 3000 символов');return Response.json(analyzeNeed(b.description));}
 if(b.action==='role')return fail('Роль закреплена за учётной записью',403);
 if(b.action==='portfolio'){if(current!=='candidate')return fail('Только для кандидата',403);const old=await read(owner,'profile','me');if(!old)return fail('Сначала сохраните основной профиль');let portfolio;try{portfolio=validatePortfolio(b.portfolio);}catch(e:any){return fail(e.message);}await put(owner,'profile',{...old,portfolio});return Response.json({ok:true});}
 if(b.action==='profile'){if(current!=='candidate')return fail('Только для кандидата',403);if(!b.name?.trim()||!b.email?.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/)||!roles.includes(b.role))return fail('Проверьте имя, почту и специализацию');const old=await read(owner,'profile','me');if(!b.consent)return fail('Нужно согласие на обработку данных');let portfolio;try{portfolio=validatePortfolio(b.portfolio===undefined?old?.portfolio||[]:b.portfolio);}catch(e:any){return fail(e.message);}let candidateFields;try{candidateFields=validateCandidateFields(b.industry,b.softSkills);}catch(e:any){return fail(e.message);}let personal;try{personal=validateEducation(b.birthDate===undefined?old?.birthDate||'':b.birthDate,b.education===undefined?old?.education||[]:b.education);}catch(e:any){return fail(e.message);}const same=old?.role===b.role;const profile={id:'me',...personal,...candidateFields,questionnaire:same&&old?.industry===candidateFields.industry?old?.questionnaire:undefined,name:String(b.name).slice(0,100),email:b.email,role:b.role,grade:same?old?.grade||null:null,score:same?old?.score||0:0,assessmentVersion:same?old?.assessmentVersion:undefined,verifiedAt:same?old?.verifiedAt:undefined,lastGradeChange:old?.lastGradeChange,stack:[...new Set((Array.isArray(b.stack)?b.stack:String(b.stack||'').split(',')).filter((s:any)=>typeof s==='string').map((s:string)=>s.trim().slice(0,60)).filter(Boolean))].slice(0,100),city:String(b.city||'').slice(0,160),format:['Удалённо','Гибрид','Офис'].includes(b.format)?b.format:'Удалённо',experience:Math.max(0,Math.min(50,Number(b.experience)||0)),bio:String(b.bio||'').slice(0,2000),portfolio,fsp:[],fspId:String(b.fspId||'').slice(0,100),consent:true,published:!!b.published};await put(owner,'profile',profile);return Response.json({ok:true});}
 if(b.action==='company'){if(current!=='employer')return fail('Только для работодателя',403);if(!b.name?.trim()||!b.contact?.trim())return fail('Заполните компанию и способ связи');const website=String(b.website||'').trim();if(website){try{if(!['http:','https:'].includes(new URL(website).protocol))return fail('Укажите сайт с http:// или https://');}catch{return fail('Проверьте адрес сайта');}}const contactEmail=String(b.contactEmail||'').trim();if(contactEmail&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contactEmail))return fail('Проверьте рабочую почту');const fields=Object.fromEntries(['industry','city','address','contactName','contactRole','phone','telegram'].map(key=>[key,String(b[key]||'').trim().slice(0,200)]));await put(owner,'company',{id:'main',name:String(b.name).slice(0,100),description:String(b.description||'').slice(0,2000),contact:String(b.contact).slice(0,150),...fields,website:website.slice(0,500),contactEmail:contactEmail.slice(0,254),size:['1–10','11–50','51–200','201–500','501–1000','Более 1000'].includes(b.size)?b.size:'Не указан',benefits:String(b.benefits||'').slice(0,2000)});return Response.json({ok:true});}
 if(b.action==='questionnaire'){if(current!=='candidate')return fail('Только для кандидата',403);const p=await read(owner,'profile','me');if(!p)return fail('Сначала сохраните профиль');let q;try{validateCandidateFields(b.industry,p.softSkills);q=validateSurvey(b);}catch(e:any){return fail(e.message);}if(p.lastGradeChange&&Date.now()-p.lastGradeChange<90*86400000)return fail('Следующая смена грейда доступна через 90 дней',409);const saved={id:'main',...q,version:1,completedAt:Date.now()};const same=p.role===q.role;await put(owner,'profile',{...p,questionnaire:saved,industry:q.industry,role:q.role,...(!same?{grade:null,score:0,verifiedAt:null,assessmentVersion:null}:{})});await put(owner,'questionnaire',saved);return Response.json({ok:true});}
 if(b.action==='startTest'){if(current!=='candidate')return fail('Только для кандидата',403);const p=await read(owner,'profile','me');if(!p)return fail('Сначала сохраните профиль');if(!grades.includes(b.grade))return fail('Неизвестный грейд');const questionnaire=await read(owner,'questionnaire','main');if(!questionnaire||questionnaire.role!==p.role||questionnaire.industry!==p.industry||questionnaire.grade!==b.grade)return fail('Сначала пройдите опрос для выбранной специализации и грейда',409);if(!await (await import('@/lib/auth')).limit('test-start:'+owner,8,86400000))return fail('Не более 8 попыток в сутки',429);if(p.lastGradeChange&&Date.now()-p.lastGradeChange<90*86400000)return fail('Следующая смена грейда доступна через 90 дней после подтверждения',409);const qs=questions(p.role,b.grade);const test={id:crypto.randomUUID(),role:p.role,industry:p.industry,questionnaire,grade:b.grade,questions:qs,created:Date.now(),used:false,version:ASSESSMENT_VERSION};await put(owner,'test',test);return Response.json({id:test.id,grade:test.grade,questions:qs.map(({answer,tolerance,...q}:any)=>q),expires:test.created+45*60000});}
 if(b.action==='submitTest'){if(current!=='candidate')return fail('Только для кандидата',403);const t=await read(owner,'test',b.id);if(!t||t.version!==ASSESSMENT_VERSION||t.used||Date.now()-t.created>45*60000)return fail('Тест завершён или истёк. Начните новый.',409);if(!Array.isArray(b.answers)||b.answers.length!==t.questions.length||b.answers.some((a:any,i:number)=>t.questions[i].kind==='number'?(typeof a!=='string'||!a.trim()||a.length>50):(!Number.isInteger(a)||a<0||a>3)))return fail('Ответьте на все вопросы');const p=await read(owner,'profile','me');if(!p||p.role!==t.role||p.industry!==t.industry)return fail('Профиль изменился. Начните новый тест.',409);if(p.lastGradeChange&&Date.now()-p.lastGradeChange<90*86400000)return fail('Грейд уже подтверждён',409);const claimed=await database().prepare("UPDATE records SET data=json_set(data,'$.used',json('true')),updated=? WHERE owner=? AND kind='test' AND json_extract(data,'$.id')=? AND json_extract(data,'$.used')=0 RETURNING id").bind(Date.now(),owner,t.id).first();if(!claimed)return fail('Тест уже проверен',409);const assessed=evaluate(t.questions,b.answers,t.grade);const result={id:t.id,...assessed,grade:t.grade,questionnaire:t.questionnaire,date:Date.now(),version:t.version||1};if(result.passed){const changed=await database().prepare("UPDATE records SET data=json_set(data,'$.grade',?,'$.score',?,'$.verifiedAt',?,'$.lastGradeChange',?,'$.assessmentVersion',?),updated=? WHERE owner=? AND kind='profile' AND json_extract(data,'$.role')=? AND COALESCE(json_extract(data,'$.lastGradeChange'),0)<=? RETURNING id").bind(t.grade,result.score,result.date,result.date,t.version||1,result.date,owner,t.role,Date.now()-90*86400000).first();if(!changed)return fail('Профиль или грейд уже изменился. Результат не применён.',409);}await put(owner,'result',result);return Response.json(result);}
 if(b.action==='history'){if(current!=='candidate')return fail('Только для кандидата',403);return Response.json({results:await list(owner,'result')});}
 if(b.action==='invite'){if(current!=='employer')return fail('Только для работодателя',403);const isSeed=seed().some(c=>c.id===b.candidateId);const p=isSeed?seed().find(c=>c.id===b.candidateId):await read(String(b.candidateId),'profile','me');if(!p?.grade||!p.published||!p.consent)return fail('Кандидат недоступен');const min=Number(b.min),max=Number(b.max);if(!Number.isInteger(min)||!Number.isInteger(max)||min<1||max<min||max>10000000||!b.description?.trim())return fail('Укажите предложение и корректную вилку зарплаты');let assignment:any=null;const a=b.assignment;if(a&&a.mode!=='none'){if(a.mode==='catalog'){const task=ASSIGNMENTS.find(t=>t.id===a.catalogId);if(!task)return fail('Выберите задание из каталога');assignment={...task,source:'catalog'};}else if(a.mode==='custom'){if(typeof a.title!=='string'||!a.title.trim()||a.title.length>120||typeof a.description!=='string'||!a.description.trim()||a.description.length>10000)return fail('Заполните название и условие задания');assignment={title:a.title.trim(),description:a.description.trim(),source:'custom'};}else return fail('Неизвестный тип задания');}const company=await read(owner,'company','main');if(!company)return fail('Сначала заполните профиль компании');await put(owner,'invitation',{id:crypto.randomUUID(),candidateId:b.candidateId,candidateOwner:isSeed?null:b.candidateId,candidateName:p.name,company:company.name,contact:company.contact,description:String(b.description).slice(0,3000),min,max,assignment,status:'sent',created:Date.now()});return Response.json({ok:true});}
 if(b.action==='submitSolution'){if(current!=='candidate')return fail('Только для кандидата',403);const entry=await candidateInvitation(owner,b.id);const i=entry?.value;if(!i)return fail('Приглашение не найдено',404);if(!i.assignment)return fail('В приглашении нет задания');if(i.status==='declined')return fail('Предложение отклонено',409);if(typeof b.text!=='string'||!b.text.trim()||b.text.length>15000)return fail('Введите ответ до 15 000 символов');if(b.url!=null&&typeof b.url!=='string')return fail('Проверьте ссылку');const url=(b.url||'').trim();if(url.length>1000)return fail('Ссылка слишком длинная');if(url){try{if(!['https:','http:'].includes(new URL(url).protocol))throw new Error();}catch{return fail('Укажите ссылку с http:// или https://');}}await put(entry!.employer,'invitation',{...i,solution:{text:b.text.trim(),url,submittedAt:Date.now()}});return Response.json({ok:true});}
 if(b.action==='respond'){if(current!=='candidate')return fail('Только для кандидата',403);const entry=await candidateInvitation(owner,b.id);const i=entry?.value;if(!i)return fail('Приглашение не найдено',404);if(!['accepted','declined','viewed'].includes(b.status))return fail('Недопустимый статус');if(['accepted','declined'].includes(i.status))return fail('Ответ уже отправлен',409);await put(entry!.employer,'invitation',{...i,status:b.status});return Response.json({ok:true});}
 return fail('Неизвестное действие');}catch(e){console.error(e);return fail('Не удалось сохранить данные. Попробуйте ещё раз.',503);}}
