// Independent human pilot kit; empty data never produces claimed validation results.
const fs=require('fs'),path=require('path'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),cache={};
function load(name){const file=path.resolve(root,name+'.ts');if(cache[file])return cache[file].exports;const m={exports:{}};cache[file]=m;const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;new Function('exports','require','module',code)(m.exports,p=>p.startsWith('.')?load(path.relative(root,path.join(path.dirname(file),p))):require(p),m);return m.exports;}
const assessment=load('lib/assessment'),domain=load('lib/domain');
const [mode,folder='outputs/pilot']=process.argv.slice(2),out=path.resolve(folder);
function json(file,data){fs.writeFileSync(path.join(out,file),JSON.stringify(data,null,2));}
function csv(rows){return rows.map(row=>row.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n');}
function readCsv(file){const source=fs.readFileSync(file,'utf8').replace(/^\uFEFF/,'');let rows=[],row=[],cell='',quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c===','||c==='\n')){row.push(cell.replace(/\r$/,''));cell='';if(c==='\n'){rows.push(row);row=[];}}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const header=rows.shift();return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(header.map((h,i)=>[h,r[i]||''])));}
const page=data=>`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Пилот ФСП Talent</title><style>body{font:18px system-ui;max-width:850px;margin:30px auto;padding:20px;color:#202938}article{border:1px solid #ddd;padding:20px;margin:20px 0;border-radius:12px}label{display:block;margin:12px 0}button{padding:15px;background:#dc2439;color:white;border:0;border-radius:8px}input[type=text]{font:inherit;padding:10px;width:90%}</style><h1>Независимый пилот ФСП Talent</h1><p>Участник ${data.participantId} · ${data.role} · ${data.grade} · форма ${data.form}</p><p>До 45 минут. Не используйте ключи ответов. Форма работает локально, ответы не отправляются в интернет. Сохраните файл и передайте координатору. Не указывайте ФИО или почту.</p><form id="test"></form><script>const data=${JSON.stringify(data).replaceAll('<','\\u003c')},started=Date.now(),form=document.getElementById('test');data.questions.forEach((q,i)=>{const a=document.createElement('article'),h=document.createElement('h3');h.textContent=(i+1)+'. '+q.text;a.append(h);if(q.kind==='number'){const input=document.createElement('input');input.type='text';input.name='q'+i;input.required=true;input.inputMode='decimal';a.append(input);}else q.options.forEach((o,n)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='q'+i;input.value=n;input.required=true;label.append(input,document.createTextNode(' '+o));a.append(label);});form.append(a);});const label=document.createElement('label');label.innerHTML='<input name="assistance" type="checkbox"> Я использовал(а) внешнюю помощь';form.append(label);const button=document.createElement('button');button.textContent='Завершить и сохранить ответы';form.append(button);form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),answers=data.questions.map((q,i)=>q.kind==='number'?String(f.get('q'+i)):Number(f.get('q'+i)));const result={participantId:data.participantId,trialId:data.trialId,answers,seconds:Math.round((Date.now()-started)/1000),assistance:f.has('assistance'),completedAt:new Date().toISOString()};const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=data.trialId+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};</script></html>`;
if(mode==='prepare'){
 if(fs.existsSync(path.join(out,'manifest-private.json')))throw Error('Existing pilot must not be overwritten; choose a new folder');
 fs.mkdirSync(out,{recursive:true});for(const dir of ['participants','submissions'])fs.mkdirSync(path.join(out,dir));
 const trials=[],experts=[['participantId','role','expertGrade','expertId','notes']];let index=0;
 for(const role of domain.roles)for(const grade of domain.grades){const id='P'+String(++index).padStart(2,'0');experts.push([id,role,'','','']);for(const form of ['A','B']){const trialId=id+'-'+form,questions=assessment.generateAssessment(role,grade);trials.push({participantId:id,trialId,role,grade,form,questions});const safe=questions.map(({answer,tolerance,...q})=>q);fs.writeFileSync(path.join(out,'participants',trialId+'.html'),page({participantId:id,trialId,role,grade,form,questions:safe}));}}
 const needs=[{id:'N1',role:'Backend',grade:'Middle',stack:'Python,PostgreSQL',format:'Удалённо',description:'Разработка API на Python и PostgreSQL.'},{id:'N2',role:'Frontend',grade:'Middle',stack:'React,TypeScript',format:'Гибрид',description:'Разработка интерфейсов на React и TypeScript.'},{id:'N3',role:'Data Science',grade:'Middle',stack:'Python,Pandas',description:'Анализ данных и рекомендательные системы.'},{id:'N4',role:'Backend',grade:'Senior',stack:'Go,Kubernetes',description:'Архитектура сервисов на Go и Kubernetes.'}];
 const candidates=domain.seed().map(({email,name,...c})=>({...c,name:'Кандидат '+c.id}));
 json('manifest-private.json',{version:assessment.ASSESSMENT_VERSION,created:new Date().toISOString(),trials});json('ranking-dataset.json',{source:'Synthetic profiles and authored needs; expert judgments not collected',needs,candidates});
 fs.writeFileSync(path.join(out,'expert-grades.csv'),'\uFEFF'+csv(experts));fs.writeFileSync(path.join(out,'relevance-labels.csv'),'\uFEFF'+csv([['needId','candidateId','relevance','expertId','notes'],...needs.flatMap(n=>candidates.map(c=>[n.id,c.id,'','','']))]));
 console.log(JSON.stringify({status:'prepared_not_run',forms:trials.length,participants:experts.length-1,folder:out}));
}else if(mode==='analyze'){
 const manifest=JSON.parse(fs.readFileSync(path.join(out,'manifest-private.json'))),experts=readCsv(path.join(out,'expert-grades.csv')),seen=new Set(),results=[],excluded=[];
 for(const file of fs.readdirSync(path.join(out,'submissions')).filter(f=>f.endsWith('.json'))){const s=JSON.parse(fs.readFileSync(path.join(out,'submissions',file))),t=manifest.trials.find(t=>t.trialId===s.trialId&&t.participantId===s.participantId);if(!t||seen.has(s.trialId)||!Array.isArray(s.answers)||s.answers.length!==t.questions.length)throw Error('Invalid or duplicate submission: '+file);seen.add(s.trialId);if(s.assistance||!Number.isFinite(s.seconds)||s.seconds<0||s.seconds>2700){excluded.push({trialId:s.trialId,reason:'assistance or time outside protocol'});continue;}const evaluation=assessment.evaluate(t.questions,s.answers,t.grade),expert=experts.find(e=>e.participantId===s.participantId&&e.role===t.role);const expected=expert?.expertId&&domain.grades.includes(expert.expertGrade)?domain.grades.indexOf(expert.expertGrade)>=domain.grades.indexOf(t.grade):null;results.push({trialId:t.trialId,participantId:t.participantId,form:t.form,role:t.role,grade:t.grade,...evaluation,seconds:s.seconds,expertExpectedPass:expected,agrees:expected===null?null:expected===evaluation.passed});}
 const judged=results.filter(r=>r.agrees!==null),pairs=[];for(const id of new Set(results.map(r=>r.participantId))){const a=results.find(r=>r.participantId===id&&r.form==='A'),b=results.find(r=>r.participantId===id&&r.form==='B');if(a&&b)pairs.push({participantId:id,sameDecision:a.passed===b.passed,scoreDifference:Math.abs(a.score-b.score)});}
 const dataset=JSON.parse(fs.readFileSync(path.join(out,'ranking-dataset.json'))),labels=readCsv(path.join(out,'relevance-labels.csv')),ranking=[];
 for(const n of dataset.needs){const lab=new Map(labels.filter(l=>l.needId===n.id&&l.expertId&&/^[012]$/.test(l.relevance)).map(l=>[l.candidateId,Number(l.relevance)]));if(dataset.candidates.some(c=>!lab.has(c.id)))continue;const candidates=dataset.candidates.filter(c=>c.role===n.role&&c.grade===n.grade);const scored=[...candidates].sort((a,b)=>domain.rank(b,n).value-domain.rank(a,n).value),baseline=[...candidates].sort((a,b)=>n.stack.split(',').filter(s=>b.stack.includes(s)).length-n.stack.split(',').filter(s=>a.stack.includes(s)).length||a.id.localeCompare(b.id));const metric=list=>{const top=list.slice(0,5),dcg=items=>items.reduce((sum,c,i)=>sum+(2**lab.get(c.id)-1)/Math.log2(i+2),0),ideal=dcg([...candidates].sort((a,b)=>lab.get(b.id)-lab.get(a.id)).slice(0,5));return {precisionAt1:top.length?Number(lab.get(top[0].id)>0):null,precisionAt5FixedDenominator:top.filter(c=>lab.get(c.id)>0).length/5,availablePrecision:top.length?top.filter(c=>lab.get(c.id)>0).length/top.length:null,ndcgAt5:ideal?dcg(top)/ideal:null};};ranking.push({needId:n.id,available:candidates.length,fewerThanFive:candidates.length<5,platform:metric(scored),stackBaseline:metric(baseline)});}
 const report={status:results.length||ranking.length?'exploratory_human_data':'awaiting_independent_participants',assessmentVersion:manifest.version,received:seen.size,validForms:results.length,independentJudgedForms:judged.length,agreement:judged.length?judged.filter(r=>r.agrees).length/judged.length:null,pairedParticipants:pairs.length,retestAgreement:pairs.length?pairs.filter(p=>p.sameDecision).length/pairs.length:null,meanAbsoluteScoreDifference:pairs.length?pairs.reduce((s,p)=>s+p.scoreDifference,0)/pairs.length:null,excluded,results,pairs,ranking,limitations:['Small exploratory pilot, not proof of grade validity','Expert grades must be collected blind before results','Ranking dataset is synthetic; independent labels do not make profiles real','No confidence intervals claimed; insufficient sample size','Two forms assess repeatability; task bank content overlaps']};json('pilot-results.json',report);console.log(JSON.stringify({status:report.status,validForms:results.length,judgedForms:judged.length,rankingNeeds:ranking.length}));
}else throw Error('Usage: node scripts/pilot.cjs prepare|analyze <folder>');
